name: Use Secrets Example

on:
  push:
    branches:
      - main

jobs:
  display-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display API Key
        run: echo "Your API Key is: '${{ secrets.API_KEY }}'"
